#!/bin/sh

~rbutler/public/courses/pp6330/kj p2

# 2100 x 3200

echo
echo RMB  "   1  26.174957"
echo RMB  "3387   0.014984"
echo
echo RMB  "~1 secs"
echo
echo "--------------------------- 16 threads -----------------------------"
echo
/usr/bin/time -p  ./p2  2100 3200 100 100 100 400 0.015  16
echo
pwd
echo
